Repository redis/redis-vl-python, pull requests merged in 2023-08, with the labels that each got.

#30 Introduce SearchIndex.query
  docs/api/searchindex.rst
  docs/conf.py
  docs/examples/openai_qna.ipynb
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/hybrid_queries_02.ipynb
  redisvl/index.py
  redisvl/query.py
  tests/integration/test_simple.py
  tests/integration/test_simple_async.py
Labels: enhancement, query, index

#37 Documentation Update
  docs/_templates/layout.html
  docs/user_guide/getting_started_01.ipynb
Labels: documentation

#38 PyPI Infrastructure
  .github/workflows/publish.yml
  redisvl/__init__.py
  redisvl/cli/index.py
  redisvl/cli/log.py
  redisvl/cli/main.py
  redisvl/cli/version.py
  redisvl/version.py
  setup.cfg
  setup.py
Labels: CI/CD, release

#39 Fix to CD pipeline
  .github/workflows/publish.yml
Labels: CI/CD, release

#40 Fix to CD pipeline
  .github/workflows/publish.yml
Labels: CI/CD, release

#41 Fix to CD pipeline
  .github/workflows/publish.yml
Labels: CI/CD, release

#44 Vectorizer improvements
  redisvl/__init__.py
  redisvl/cli/index.py
  redisvl/cli/log.py
  redisvl/cli/main.py
  redisvl/cli/version.py
  redisvl/vectorize/base.py
  redisvl/vectorize/text/huggingface.py
  redisvl/vectorize/text/openai.py
  tests/integration/test_vectorizers.py
Labels: enhancement

#46 rvl stats and Formatting for index info
  docs/user_guide/getting_started_01.ipynb
  redisvl/cli/index.py
  redisvl/cli/main.py
  redisvl/cli/stats.py
  redisvl/cli/utils.py
  redisvl/vectorize/text/openai.py
  requirements-dev.txt
  requirements.txt
Labels: enhancement, CLI

#45 Refactor filtering approach
  docs/examples/openai_qna.ipynb
  docs/user_guide/hybrid_queries_02.ipynb
  docs/user_guide/llmcache_03.ipynb
  redisvl/index.py
  redisvl/query.py
  redisvl/query/__init__.py
  redisvl/query/filter.py
  redisvl/query/query.py
  tests/integration/test_query.py
  tests/test_filter.py
Labels: enhancement, query, breaking

#48 0.0.3 Documentation Update
  README.md
  docs/_static/gallery-images/RedisOpenAI-QnA.png
  docs/_static/gallery-images/hotel-recommender.png
  docs/_static/gallery.yaml
  docs/api/filter.rst
  docs/api/vectorizer.rst
  docs/changelog.rst
  docs/conf.py
  docs/examples/index.md
  docs/index.md
  docs/user_guide/embedding_creation.rst
  docs/user_guide/hybrid_queries_02.ipynb
  docs/user_guide/index.md
  docs/user_guide/jupyterutils.py
  docs/user_guide/vectorizers_03.ipynb
  redisvl/query/filter.py
Labels: documentation, enhancement

#49 0.0.3 release
  README.md
  redisvl/version.py
  setup.py
Labels: release

#50 Downgrade pydantic to 1.x
  redisvl/index.py
  redisvl/schema.py
  requirements.txt
  tests/integration/test_simple_async.py
Labels: bug

#51 Add FilterQuery
  redisvl/cli/index.py
  redisvl/cli/main.py
  redisvl/cli/stats.py
  redisvl/cli/utils.py
  redisvl/query/__init__.py
  redisvl/query/filter.py
  redisvl/query/query.py
  redisvl/schema.py
  redisvl/vectorize/text/huggingface.py
  redisvl/vectorize/text/openai.py
  tests/integration/test_query.py
  tests/integration/test_simple_async.py
Labels: enhancement, query

#53 Incorporate notebook tests
  .github/workflows/run_tests.yml
  .gitignore
  docs/examples/openai_qna.ipynb
  docs/user_guide/hybrid_queries_02.ipynb
  docs/user_guide/llmcache_03.ipynb
  docs/user_guide/vectorizers_03.ipynb
  requirements-dev.txt
Labels: enhancement, CI/CD

#56 Run mypy tests on commit
  .github/workflows/lint.yml
  Makefile
  redisvl/index.py
  redisvl/llmcache/semantic.py
  redisvl/query/__init__.py
  redisvl/query/filter.py
  redisvl/query/query.py
  redisvl/utils/utils.py
  redisvl/vectorize/base.py
  redisvl/vectorize/text/huggingface.py
  redisvl/vectorize/text/openai.py
  tests/integration/test_query.py
Labels: enhancement, CI/CD

#57 Add `-u` (`--url`) option in CLI
  redisvl/cli/utils.py
Labels: enhancement, CLI
