Repository redis/redis-vl-python, pull requests merged in 2023-11, with the labels that each got.

#72 Improve RedisVL filter handling, docs, and examples
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/hybrid_queries_02.ipynb
  redisvl/index.py
  redisvl/query/filter.py
  redisvl/query/query.py
  redisvl/schema.py
  tests/integration/test_query.py
  tests/test_filter.py
  tests/unit/test_filter.py
  tests/unit/test_index.py
  tests/unit/test_schema.py
  tests/unit/test_token_escaper.py
Labels: enhancement

#73 Test multiple versions of Python, Redis Stack, and hiredis option
  .github/workflows/run_tests.yml
  README.md
  tests/integration/test_vectorizers.py
Labels: CI/CD, maintenance

#77 Add MetadataSchemaGenerator
  redisvl/schema.py
  tests/integration/test_vectorizers.py
  tests/unit/test_schema.py
Labels: enhancement

#80 Semantic cache interface update
  docs/user_guide/llmcache_03.ipynb
  redisvl/llmcache/__init__.py
  redisvl/llmcache/base.py
  redisvl/llmcache/semantic.py
  tests/integration/test_llmcache.py
  tests/unit/test_query_unit.py
Labels: enhancement, breakingchange

#81 Doc update 0.0.5
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  docs/_static/concept-images/Chains.svg
  docs/_static/concept-images/cosine_similarity.png
  docs/_static/concept-images/cosine_similarity3d.png
  docs/_static/concept-images/dataset.png
  docs/_static/concept-images/dataset2.png
  docs/_static/concept-images/ecommerce.png
  docs/_static/concept-images/embedding-creation.png
  docs/_static/concept-images/embeddings-redis.png
  docs/_static/concept-images/embeddings.png
  docs/_static/concept-images/euclidean3d.png
  docs/_static/concept-images/euclidean_metric.png
  docs/_static/concept-images/images/activate-database-button.png
  docs/_static/concept-images/images/create-subscription-button.png
  docs/_static/concept-images/images/new-database-button.png
  docs/_static/concept-images/images/new-subscriptions-button.png
  docs/_static/concept-images/indexes.svg
  docs/_static/concept-images/output.png
  docs/_static/concept-images/outputagents.png
  docs/_static/concept-images/vdb_architect.png
  docs/_static/css/sidebar.css
  docs/_static/gallery-images/arxiv-search.png
  docs/_static/gallery-images/bytewax-redis.png
  docs/_static/gallery-images/chat-your-pdf.png
  docs/_static/gallery.yaml
  docs/_static/js/sidebar.js
  docs/_static/version_names.json
  docs/_templates/custom_sidebar.html
  docs/api/vectorizer.rst
  docs/conf.py
  docs/examples/index.md
  docs/index.md
  docs/overview/installation.md
  docs/overview/schema.md
  docs/user_guide/cli.ipynb
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/hybrid_queries_02.ipynb
  docs/user_guide/index.md
  docs/versions.rst
  redisvl/version.py
  setup.py
Labels: documentation, enhancement

#83 Add more query documentation
  docs/_static/concept-images/Chains.svg
  docs/_static/concept-images/cosine_similarity.png
  docs/_static/concept-images/cosine_similarity3d.png
  docs/_static/concept-images/dataset.png
  docs/_static/concept-images/dataset2.png
  docs/_static/concept-images/ecommerce.png
  docs/_static/concept-images/embedding-creation.png
  docs/_static/concept-images/embeddings-redis.png
  docs/_static/concept-images/embeddings.png
  docs/_static/concept-images/euclidean3d.png
  docs/_static/concept-images/euclidean_metric.png
  docs/_static/concept-images/images/activate-database-button.png
  docs/_static/concept-images/images/create-subscription-button.png
  docs/_static/concept-images/images/new-database-button.png
  docs/_static/concept-images/images/new-subscriptions-button.png
  docs/_static/concept-images/indexes.svg
  docs/_static/concept-images/output.png
  docs/_static/concept-images/outputagents.png
  docs/_static/concept-images/vdb_architect.png
  docs/api/cache.rst
  docs/api/query.rst
  docs/overview/schema.md
Labels: documentation, enhancement
