Repository redis/redis-vl-python, pull requests merged in 2024-08, with the labels that each got.

#180 adds semantic cache scoped access and additional functionality
  redisvl/extensions/llmcache/base.py
  redisvl/extensions/llmcache/semantic.py
  redisvl/utils/utils.py
  tests/integration/test_llmcache.py
Labels: enhancement, feature

#195 Use pydantic for cache entries and hits
  docs/user_guide/llmcache_03.ipynb
  redisvl/extensions/llmcache/base.py
  redisvl/extensions/llmcache/schema.py
  redisvl/extensions/llmcache/semantic.py
  redisvl/index/index.py
  tests/integration/test_llmcache.py
  tests/unit/test_llmcache_schema.py
Labels: enhancement

#189 Update readme and documentation
  README.md
  docs/_static/js/sidebar.js
  docs/api/cache.rst
  docs/api/index.md
  docs/api/session_manager.rst
  docs/api/vectorizer.rst
  docs/overview/cli.ipynb
  pyproject.toml
  redisvl/extensions/llmcache/base.py
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/utils/vectorize/text/custom.py
  redisvl/version.py
Labels: documentation, enhancement

#201 Fix semantic cache with empty metadata
  redisvl/extensions/llmcache/schema.py
  redisvl/extensions/llmcache/semantic.py
  tests/integration/test_llmcache.py
Labels: bug

#200 update project readme and schema definitions
  README.md
  schemas/schema.yaml
Labels: documentation

#202 Support distance threshold override
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/session_manager/semantic_session.py
  tests/integration/test_llmcache.py
  tests/integration/test_session_manager.py
Labels: enhancement

#206 Release 0.3.1
  docs/_static/version_names.json
  docs/conf.py
  docs/overview/cli.ipynb
  pyproject.toml
  redisvl/version.py
Labels: release

#208 Fix cache schema overwrite
  redisvl/extensions/llmcache/semantic.py
  tests/integration/test_llmcache.py
Labels: bug
