Repository redis/redis-vl-python, pull requests merged in 2024-05, with the labels that each got.

#139 Initial reranker integration in RedisVL
  .github/workflows/run_tests.yml
  CONTRIBUTING.md
  conftest.py
  docs/api/index.md
  docs/api/reranker.rst
  docs/api/vectorizer.rst
  redisvl/utils/rerank/__init__.py
  redisvl/utils/rerank/base.py
  redisvl/utils/rerank/cohere.py
  redisvl/utils/vectorize/base.py
  redisvl/utils/vectorize/text/azureopenai.py
  redisvl/utils/vectorize/text/cohere.py
  redisvl/utils/vectorize/text/huggingface.py
  redisvl/utils/vectorize/text/openai.py
  redisvl/utils/vectorize/text/vertexai.py
  scripts.py
  tests/integration/test_flow_async.py
  tests/integration/test_rerankers.py
  tests/integration/test_vectorizers.py
  tests/unit/test_async_search_index.py
Labels: enhancement

#146 Repackage documentation and apply poetry updates
  CONTRIBUTING.md
  docs/_static/Redis_Favicon_144x144_Red.png
  docs/_static/Redis_Favicon_16x16_Red.png
  docs/_static/Redis_Favicon_32x32_Red.png
  docs/_static/Redis_Logo_Red_RGB.svg
  docs/_static/android-chrome-192x192.png
  docs/_static/android-chrome-512x512.png
  docs/_static/apple-touch-icon.png
  docs/_static/favicon-16x16.png
  docs/_static/favicon-32x32.png
  docs/_static/favicon.ico
  docs/_static/js/sidebar.js
  docs/_static/redis-cube-red-white-rgb.svg
  docs/_static/site.webmanifest
  docs/conf.py
  docs/requirements-doc.txt
  docs/user_guide/index.md
  docs/user_guide/rerankers_06.ipynb
  poetry.lock
  pyproject.toml
  redisvl/utils/rerank/cohere.py
  scripts.py
Labels: documentation

#147 Bump to 0.2.0
  docs/conf.py
  docs/overview/cli.ipynb
  pyproject.toml
  redisvl/version.py
Labels: documentation

#153 temporarily disable codecov failures
  .github/workflows/run_tests.yml
Labels: bug

#150 Reranker implementation using Cross Encoders (HuggingFace / SentenceT…
  docs/user_guide/rerankers_06.ipynb
  redisvl/utils/rerank/__init__.py
  redisvl/utils/rerank/hf_cross_encoder.py
  tests/integration/test_rerankers.py
  tests/unit/test_cross_encoder_reranker.py
Labels: enhancement

#148 feat: adds optional sorting parameter to FilterQuery
  redisvl/query/query.py
  tests/integration/test_query.py
  tests/unit/test_query_types.py
Labels: enhancement

#154 Rename repo to new location
  CONTRIBUTING.md
  README.md
  docs/conf.py
  docs/examples/index.md
  docs/overview/installation.md
  docs/user_guide/vectorizers_04.ipynb
  pyproject.toml
Labels: documentation
