Repository redis/redis-vl-python, pull requests merged in 2024-07, with the labels that each got.

#173 Fix index loading empty array
  redisvl/index/storage.py
  tests/unit/test_async_search_index.py
  tests/unit/test_search_index.py
Labels: bug

#174 Enable creating an index "from_existing"
  redisvl/index/index.py
  redisvl/redis/connection.py
  redisvl/redis/constants.py
  tests/integration/test_async_search_index.py
  tests/integration/test_connection.py
  tests/integration/test_search_index.py
Labels: enhancement

#177 adds check to ensure correct embedding vector dimensions are used
  redisvl/extensions/llmcache/semantic.py
  tests/integration/test_llmcache.py
Labels: bug

#141 Introduce the LLM session manager classes
  conftest.py
  docs/user_guide/index.md
  docs/user_guide/session_manager_07.ipynb
  redisvl/extensions/session_manager/__init__.py
  redisvl/extensions/session_manager/base_session.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/extensions/session_manager/standard_session.py
  tests/integration/test_session_manager.py
Labels: enhancement

#179 Add ability to clear ALL data associated with an index
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/vectorizers_04.ipynb
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/index/index.py
  redisvl/query/__init__.py
  schemas/schema.yaml
  tests/integration/test_async_search_index.py
  tests/integration/test_flow.py
  tests/integration/test_flow_async.py
  tests/integration/test_search_index.py
  tests/integration/test_vectorizers.py
Labels: enhancement

#178 Improve caching ttl tests
  redisvl/extensions/llmcache/semantic.py
  tests/integration/test_llmcache.py
Labels: enhancement

#181 resets cache ttl when no arg is passed
  redisvl/extensions/llmcache/base.py
  tests/integration/test_llmcache.py
Labels: bug

#187 Enhance semantic router loading
  docs/user_guide/router.yaml
  docs/user_guide/semantic_router_08.ipynb
  redisvl/extensions/router/semantic.py
  redisvl/schema/schema.py
  redisvl/utils/utils.py
  redisvl/utils/vectorize/__init__.py
  redisvl/utils/vectorize/base.py
  redisvl/utils/vectorize/text/azureopenai.py
  redisvl/utils/vectorize/text/cohere.py
  redisvl/utils/vectorize/text/custom.py
  redisvl/utils/vectorize/text/huggingface.py
  redisvl/utils/vectorize/text/mistral.py
  redisvl/utils/vectorize/text/openai.py
  redisvl/utils/vectorize/text/vertexai.py
  schemas/semantic_router.yaml
  tests/integration/test_semantic_router.py
  tests/unit/test_schema.py
Labels: enhancement

#190 Support inorder query param
  redisvl/query/query.py
  tests/unit/test_query_types.py
Labels: enhancement

#188 Standardize extensions redis init
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/router/semantic.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/extensions/session_manager/standard_session.py
  tests/integration/test_llmcache.py
  tests/integration/test_semantic_router.py
  tests/integration/test_session_manager.py
Labels: bug, enhancement

#192 Refactor search index to improve connection handling
  docs/examples/openai_qna.ipynb
  docs/user_guide/getting_started_01.ipynb
  redisvl/extensions/session_manager/standard_session.py
  redisvl/index/index.py
  redisvl/redis/connection.py
  tests/integration/test_async_search_index.py
  tests/integration/test_connection.py
  tests/integration/test_flow_async.py
Labels: bug

#193 Makes setting scope fully optional in session managers
  conftest.py
  docs/user_guide/session_manager_07.ipynb
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/session_manager/base_session.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/extensions/session_manager/standard_session.py
  tests/integration/test_llmcache.py
  tests/integration/test_session_manager.py
Labels: enhancement

#194 Use ChatMessage pydantic model
  redisvl/extensions/router/schema.py
  redisvl/extensions/router/semantic.py
  redisvl/extensions/session_manager/base_session.py
  redisvl/extensions/session_manager/schema.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/extensions/session_manager/standard_session.py
  redisvl/utils/utils.py
  tests/unit/test_session_schema.py
Labels: enhancement
