Repository redis/redis-vl-python, pull requests merged in 2024-09, with the labels that each got.

#211 Refactor query classes
  docs/api/query.rst
  docs/user_guide/hybrid_queries_02.ipynb
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/extensions/session_manager/standard_session.py
  redisvl/index/index.py
  redisvl/query/__init__.py
  redisvl/query/query.py
  tests/integration/test_llmcache.py
  tests/integration/test_session_manager.py
  tests/unit/test_query_types.py
Labels: enhancement

#216 Update cache check logic
  redisvl/extensions/llmcache/semantic.py
  tests/integration/test_llmcache.py
Labels: bug

#217 Support semantic cache TTL overrides on writes
  redisvl/extensions/llmcache/semantic.py
  tests/integration/test_llmcache.py
Labels: enhancement

#221 DOC-4198: add TCEs to the vector query page
  doctests/data/query_vector.json
  doctests/data/query_vector_idx.yaml
  doctests/query_vector.py
Labels: documentation
