Repository redis/redis-vl-python, pull requests merged in 2024-10, with the labels that each got.

#227 Fix module version checks
  redisvl/exceptions.py
  redisvl/index/index.py
  redisvl/redis/connection.py
  tests/integration/test_connection.py
  tests/integration/test_llmcache.py
  tests/integration/test_semantic_router.py
  tests/integration/test_session_manager.py
Labels: bug

#228 Bump to 0.3.4
  docs/_static/version_names.json
  docs/conf.py
  docs/overview/cli.ipynb
  pyproject.toml
  redisvl/extensions/llmcache/semantic.py
  redisvl/version.py
Labels: release

#230 Expose aggregation API from SearchIndex
  redisvl/exceptions.py
  redisvl/extensions/router/semantic.py
  redisvl/index/index.py
  tests/integration/test_async_search_index.py
  tests/integration/test_search_index.py
Labels: enhancement

#233 Allow manual, user-defined strings as filters on queries
  docs/user_guide/hybrid_queries_02.ipynb
  redisvl/query/query.py
  tests/integration/test_query.py
  tests/unit/test_query_types.py
Labels: enhancement

#234 Release 0.3.5
  docs/_static/version_names.json
  docs/overview/cli.ipynb
  pyproject.toml
  redisvl/version.py
Labels: release

#236 Expose show_progress_bar
  redisvl/utils/vectorize/text/huggingface.py
Labels: enhancement

#240 Release 0.3.6
  docs/_static/version_names.json
  docs/overview/cli.ipynb
  pyproject.toml
  redisvl/index/index.py
  redisvl/version.py
Labels: release
