Repository redis/redis-vl-python, pull requests merged in 2024-04, with the labels that each got.

#136 Address schema serialization bug
  redisvl/schema/schema.py
  tests/unit/test_schema.py
Labels: bug

#138 bump to 0.1.3
  docs/_static/version_names.json
  docs/conf.py
  docs/overview/cli.ipynb
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/hash_vs_json_05.ipynb
  redisvl/version.py
  setup.py
Labels: enhancement

#131 Add support for AzureOpenAI
  conftest.py
  docs/user_guide/vectorizers_04.ipynb
  redisvl/utils/vectorize/__init__.py
  redisvl/utils/vectorize/text/azureopenai.py
  tests/integration/test_vectorizers.py
Labels: enhancement

#134 Poetry for Dependency Management and TestContainers for Integration Testing
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/run_tests.yml
  .github/workflows/test-publish.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  conftest.py
  poetry.lock
  pyproject.toml
  requirements-all.txt
  requirements-dev.txt
  requirements.txt
  scripts.py
  setup.cfg
  setup.py
  tests/docker-compose.yml
  tests/integration/test_connection.py
  tests/integration/test_flow_async.py
  tests/integration/test_llmcache.py
  tests/integration/test_query.py
  tests/integration/test_search_results.py
  tests/integration/test_vectorizers.py
  tests/unit/test_async_search_index.py
Labels: build
