Repository redis/redis-vl-python, pull requests merged in 2024-02, with the labels that each got.

#103 Finalize spec for index schema and fields
  docs/_static/js/sidebar.js
  docs/api/indexschema.rst
  docs/api/searchindex.rst
  docs/examples/openai_qna.ipynb
  docs/user_guide/cli.ipynb
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/hash_vs_json_05.ipynb
  docs/user_guide/hybrid_queries_02.ipynb
  docs/user_guide/llmcache_03.ipynb
  docs/user_guide/schema.yaml
  docs/user_guide/vectorizers_04.ipynb
  redisvl/cli/index.py
  redisvl/cli/main.py
  redisvl/cli/stats.py
  redisvl/cli/utils.py
  redisvl/cli/version.py
  redisvl/index.py
  redisvl/llmcache/semantic.py
  redisvl/schema/__init__.py
  redisvl/schema/fields.py
  redisvl/schema/schema.py
  redisvl/utils/log.py
  schemas/schema.yaml
  schemas/test_hash_schema.yaml
  schemas/test_json_schema.yaml
  tests/integration/test_query.py
  tests/integration/test_simple.py
  tests/integration/test_simple_async.py
  tests/sample_hash_schema.yaml
  tests/sample_json_schema.yaml
  tests/unit/test_fields.py
  tests/unit/test_index.py
  tests/unit/test_schema.py
Labels: documentation, enhancement, breakingchange

#106 Improve redisvl module structure
  docs/examples/openai_qna.ipynb
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/llmcache_03.ipynb
  docs/user_guide/vectorizers_04.ipynb
  redisvl/extensions/__init__.py
  redisvl/extensions/llmcache/__init__.py
  redisvl/extensions/llmcache/base.py
  redisvl/extensions/llmcache/semantic.py
  redisvl/index/__init__.py
  redisvl/index/index.py
  redisvl/index/storage.py
  redisvl/llmcache/__init__.py
  redisvl/utils/vectorize/__init__.py
  redisvl/utils/vectorize/base.py
  redisvl/utils/vectorize/text/__init__.py
  redisvl/utils/vectorize/text/cohere.py
  redisvl/utils/vectorize/text/huggingface.py
  redisvl/utils/vectorize/text/openai.py
  redisvl/utils/vectorize/text/vertexai.py
  redisvl/vectorize/text/__init__.py
  tests/integration/test_llmcache.py
  tests/integration/test_vectorizers.py
  tests/unit/test_async_search_index.py
  tests/unit/test_query_types.py
  tests/unit/test_search_index.py
  tests/unit/test_storage.py
Labels: enhancement

#108 Changes to contributions page
  CONTRIBUTING.md
Labels: documentation

#109 Increase redisvl test coverage
  conftest.py
  redisvl/redis/utils.py
  tests/integration/test_llmcache.py
  tests/integration/test_search_results.py
  tests/unit/test_async_search_index.py
  tests/unit/test_search_index.py
  tests/unit/test_utils.py
Labels: enhancement

#105 Enhance README, docs, and examples
  README.md
  docs/api/cache.rst
  docs/api/filter.rst
  docs/api/query.rst
  docs/api/schema.rst
  docs/api/searchindex.rst
  docs/api/vectorizer.rst
  docs/user_guide/getting_started_01.ipynb
  redisvl/extensions/llmcache/semantic.py
  redisvl/index/index.py
  redisvl/query/filter.py
  redisvl/query/query.py
  redisvl/redis/connection.py
  redisvl/schema/schema.py
  tests/integration/test_llmcache.py
  tests/integration/test_query.py
  tests/integration/test_search_results.py
  tests/unit/test_async_search_index.py
  tests/unit/test_search_index.py
  tests/unit/test_utils.py
Labels: documentation, enhancement

#118 Update Cohere client setting
  redisvl/utils/vectorize/text/cohere.py
Labels: enhancement

#119 Update and pin package dependency ranges
  requirements.txt
Labels: bug

#120 Fix index.fetch() bug
  redisvl/index/index.py
  tests/integration/test_flow.py
  tests/integration/test_flow_async.py
Labels: bug

#123 Patch requirements
  setup.py
Labels: bug
