Repository redis/redis-vl-python, pull requests merged in 2024-06, with the labels that each got.

#155 Add client info reporting
  .gitignore
  conftest.py
  redisvl/index/index.py
  redisvl/redis/connection.py
  tests/integration/test_connection.py
Labels: enhancement

#157 Enable test pypi flow
  .github/workflows/release.yml
Labels: enhancement, CI/CD

#164 Fix null numeric filter conditions
  redisvl/query/filter.py
  tests/integration/test_query.py
  tests/unit/test_filter.py
Labels: bug

#161 Fix typos
  docs/user_guide/llmcache_03.ipynb
Labels: bug, documentation

#168 Fix typo in cli.ipynb docs example
  docs/overview/cli.ipynb
Labels: documentation

#171 Support OpenAI config values in vectorizers
  redisvl/utils/vectorize/text/azureopenai.py
  redisvl/utils/vectorize/text/openai.py
  tests/integration/test_query.py
  tests/unit/test_filter.py
Labels: enhancement
