Repository redis/redis-vl-python, pull requests merged in 2024-01, with the labels that each got.

#93 Return keys on load
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/hash_vs_json_05.ipynb
  docs/user_guide/hybrid_queries_02.ipynb
  docs/user_guide/index.md
  docs/user_guide/llmcache_03.ipynb
  redisvl/index.py
  redisvl/llmcache/semantic.py
  redisvl/storage.py
  redisvl/utils/utils.py
Labels: feature

#95 Expand query support
  redisvl/index.py
  redisvl/query/query.py
  tests/integration/test_query.py
  tests/unit/test_query_types.py
  tests/unit/test_query_unit.py
Labels: enhancement

#97 Improve SemanticCache for metadata persistence
  docs/api/cache.rst
  docs/user_guide/llmcache_03.ipynb
  redisvl/index.py
  redisvl/llmcache/base.py
  redisvl/llmcache/semantic.py
  tests/integration/test_llmcache.py
Labels: enhancement

#98 Add Cohere vectorizer
  .github/workflows/run_tests.yml
  conftest.py
  docs/api/vectorizer.rst
  docs/user_guide/vectorizers_04.ipynb
  redisvl/vectorize/base.py
  redisvl/vectorize/text/__init__.py
  redisvl/vectorize/text/cohere.py
  redisvl/vectorize/text/huggingface.py
  redisvl/vectorize/text/openai.py
  redisvl/vectorize/text/vertexai.py
  setup.py
  tests/integration/test_vectorizers.py
Labels: enhancement

#99 Documentation formatting and update
  docs/api/indexschema.rst
  docs/api/searchindex.rst
  docs/api/vectorizer.rst
  docs/overview/installation.md
  pyproject.toml
  redisvl/index.py
  redisvl/llmcache/base.py
  redisvl/llmcache/semantic.py
  redisvl/query/filter.py
  redisvl/query/query.py
  redisvl/schema/fields.py
  redisvl/schema/schema.py
  redisvl/storage.py
  redisvl/utils/connection.py
  redisvl/vectorize/text/cohere.py
  redisvl/vectorize/text/huggingface.py
  redisvl/vectorize/text/openai.py
  redisvl/vectorize/text/vertexai.py
  redisvl/version.py
  setup.py
  tests/unit/test_schema.py
Labels: documentation, enhancement

#102 Fixing release drafter to work aginst the main branch
  .github/workflows/release-drafter.yml
  redisvl/vectorize/text/cohere.py
  redisvl/vectorize/text/openai.py
Labels: maintenance

#101 Upgrade to use Pydantic 2.x.x
  .gitignore
  CONTRIBUTING.md
  redisvl/index.py
  redisvl/llmcache/semantic.py
  redisvl/schema/fields.py
  redisvl/schema/schema.py
  redisvl/storage.py
  redisvl/vectorize/base.py
  redisvl/vectorize/text/cohere.py
  redisvl/vectorize/text/huggingface.py
  redisvl/vectorize/text/openai.py
  redisvl/vectorize/text/vertexai.py
  requirements.txt
  tests/unit/test_fields.py
  tests/unit/test_storage.py
Labels: enhancement
