Repository redis/redis-vl-python, pull requests merged in 2025-01, with the labels that each got.

#254 fix protobuf broken version for google (optional) dependencies
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/run_tests.yml
  poetry.lock
  pyproject.toml
Labels: bug

#256 Upgrade to readthedocs.org documentation
  .docs_static/.nojekyll
  .docs_static/CNAME
  .docs_static/index.html
  .github/workflows/run_tests.yml
  .readthedocs.yaml
  CONTRIBUTING.md
  README.md
  docs/_static/gallery-images/RedisOpenAI-QnA.png
  docs/_static/gallery-images/arxiv-search.png
  docs/_static/gallery-images/bytewax-redis.png
  docs/_static/gallery-images/chat-your-pdf.png
  docs/_static/gallery-images/hotel-recommender.png
  docs/_static/gallery.yaml
  docs/_static/js/sidebar.js
  docs/_static/version_names.json
  docs/_templates/custom_sidebar.html
  docs/_templates/versions.html
  docs/api/index.md
  docs/conf.py
  docs/examples/index.md
  docs/examples/openai_qna.ipynb
  docs/index.md
  docs/overview/cli.ipynb
  docs/overview/index.md
  docs/overview/installation.md
  docs/user_guide/getting_started_01.ipynb
  docs/user_guide/hash_vs_json_05.ipynb
  docs/user_guide/hybrid_queries_02.ipynb
  docs/user_guide/index.md
  pyproject.toml
Labels: documentation, enhancement

#257 Release version 0.3.8
  docs/overview/cli.ipynb
  docs/user_guide/getting_started_01.ipynb
  pyproject.toml
  redisvl/version.py
Labels: release

#259 Fix recommender link
  docs/_static/gallery.yaml
Labels: bug, documentation

#223 Integrate VoyageAI Vectorizer and Reranker class
  .github/workflows/run_tests.yml
  README.md
  docs/api/reranker.rst
  docs/api/vectorizer.rst
  docs/user_guide/rerankers_06.ipynb
  docs/user_guide/vectorizers_04.ipynb
  poetry.lock
  pyproject.toml
  redisvl/utils/rerank/__init__.py
  redisvl/utils/rerank/hf_cross_encoder.py
  redisvl/utils/rerank/voyageai.py
  redisvl/utils/vectorize/__init__.py
  redisvl/utils/vectorize/base.py
  redisvl/utils/vectorize/text/voyageai.py
  tests/integration/test_rerankers.py
  tests/integration/test_vectorizers.py
Labels: enhancement

#262 Standardize GH actions workflows
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/run_tests.yml
Labels: CI/CD, maintenance

#265 Fix README Redis logo src
  .coveragerc
  README.md
Labels: bug, documentation

#261 Add a default for the `dtype` field of `BaseVectorizer`
  redisvl/schema/schema.py
  redisvl/utils/vectorize/base.py
  tests/unit/test_base_vectorizer.py
Labels: bug

#264 Add a Makefile again
  CONTRIBUTING.md
  Makefile
Labels: documentation

#267 Consider vectorizer the owner of dtype
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/router/semantic.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/utils/utils.py
  tests/integration/test_llmcache.py
  tests/integration/test_semantic_router.py
  tests/integration/test_session_manager.py
  tests/unit/test_base_vectorizer.py
  tests/unit/test_utils.py
Labels: maintenance
