Repository redis/redis-vl-python, pull requests merged in 2025-02, with the labels that each got.

#270 Improve CI test runtime with pytest-xdist
  .github/workflows/lint.yml
  .github/workflows/run_tests.yml
  CONTRIBUTING.md
  Makefile
  conftest.py
  poetry.lock
  pyproject.toml
  redisvl/schema/fields.py
  redisvl/utils/vectorize/text/custom.py
  scripts.py
  tests/integration/test_connection.py
  tests/integration/test_llmcache.py
  tests/integration/test_search_results.py
  tests/integration/test_semantic_router.py
  tests/integration/test_session_manager.py
  tests/integration/test_vectorizers.py
Labels: CI/CD, maintenance

#271 Add nightly CI run and optional manual workflow dispatch
  .github/workflows/test.yml
Labels: CI/CD, maintenance

#274 Only check for workerid if workerinput is present
  conftest.py
Labels: CI/CD, maintenance

#272 Support Python 3.13
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  docs/user_guide/vectorizers_04.ipynb
  poetry.lock
  pyproject.toml
  redisvl/redis/utils.py
  tests/conftest.py
Labels: enhancement, maintenance

#277 Use ULID instead of UUID4
  docs/user_guide/getting_started_01.ipynb
  redisvl/extensions/session_manager/base_session.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/extensions/session_manager/standard_session.py
  redisvl/index/storage.py
  redisvl/utils/utils.py
  tests/unit/test_session_schema.py
Labels: enhancement

#275 Deprecate global distance_threshold with semantic router
  .gitignore
  README.md
  docs/index.md
  docs/user_guide/01_getting_started.ipynb
  docs/user_guide/02_hybrid_queries.ipynb
  docs/user_guide/03_llmcache.ipynb
  docs/user_guide/04_vectorizers.ipynb
  docs/user_guide/05_hash_vs_json.ipynb
  docs/user_guide/06_rerankers.ipynb
  docs/user_guide/07_session_manager.ipynb
  docs/user_guide/08_semantic_router.ipynb
  docs/user_guide/index.md
  docs/user_guide/router.yaml
  docs/user_guide/vectorizers_04.ipynb
  poetry.lock
  redisvl/extensions/router/schema.py
  redisvl/extensions/router/semantic.py
  schemas/semantic_router.yaml
  tests/integration/test_semantic_router.py
  tests/unit/test_route_schema.py
Labels: maintenance

#279 adds support for int8 and uint8 dtypes in vectorizers
  docs/user_guide/04_vectorizers.ipynb
  redisvl/redis/utils.py
  redisvl/schema/fields.py
  redisvl/utils/vectorize/text/azureopenai.py
  redisvl/utils/vectorize/text/bedrock.py
  redisvl/utils/vectorize/text/cohere.py
  redisvl/utils/vectorize/text/custom.py
  redisvl/utils/vectorize/text/huggingface.py
  redisvl/utils/vectorize/text/mistral.py
  redisvl/utils/vectorize/text/openai.py
  redisvl/utils/vectorize/text/vertexai.py
  redisvl/utils/vectorize/text/voyageai.py
  schemas/semantic_router.yaml
  tests/integration/test_vectorizers.py
  tests/unit/test_utils.py
Labels: enhancement

#282 Support Redis 8
  .github/workflows/test.yml
  tests/conftest.py
  tests/docker-compose.yml
  tests/integration/test_llmcache.py
Labels: enhancement

#281 Upgrade to Pydantic V2 models
  docs/user_guide/01_getting_started.ipynb
  docs/user_guide/08_semantic_router.ipynb
  redisvl/extensions/llmcache/schema.py
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/router/schema.py
  redisvl/extensions/router/semantic.py
  redisvl/extensions/session_manager/schema.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/index/storage.py
  redisvl/schema/fields.py
  redisvl/schema/schema.py
  redisvl/utils/rerank/base.py
  redisvl/utils/rerank/cohere.py
  redisvl/utils/rerank/hf_cross_encoder.py
  redisvl/utils/rerank/voyageai.py
  redisvl/utils/utils.py
  redisvl/utils/vectorize/__init__.py
  redisvl/utils/vectorize/base.py
  redisvl/utils/vectorize/text/azureopenai.py
  redisvl/utils/vectorize/text/bedrock.py
  redisvl/utils/vectorize/text/cohere.py
  redisvl/utils/vectorize/text/custom.py
  redisvl/utils/vectorize/text/huggingface.py
  redisvl/utils/vectorize/text/mistral.py
  redisvl/utils/vectorize/text/openai.py
  redisvl/utils/vectorize/text/vertexai.py
  redisvl/utils/vectorize/text/voyageai.py
  schemas/semantic_router.yaml
  tests/integration/test_llmcache.py
  tests/integration/test_semantic_router.py
  tests/unit/test_llmcache_schema.py
  tests/unit/test_route_schema.py
  tests/unit/test_session_schema.py
Labels: maintenance

#284 Patch dependabot security vulnerability in extras dependency
  poetry.lock
  pyproject.toml
Labels: bug

#285 Expand CLI usage examples and docs
  docs/overview/cli.ipynb
Labels: documentation, enhancement

#287 Add nested JSON example to docs
  docs/user_guide/05_hash_vs_json.ipynb
Labels: documentation, enhancement

#280 Refactor async client connection-handling
  README.md
  docs/user_guide/01_getting_started.ipynb
  docs/user_guide/02_hybrid_queries.ipynb
  docs/user_guide/04_vectorizers.ipynb
  docs/user_guide/05_hash_vs_json.ipynb
  redisvl/cli/index.py
  redisvl/extensions/llmcache/semantic.py
  redisvl/extensions/router/semantic.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/extensions/session_manager/standard_session.py
  redisvl/index/index.py
  redisvl/redis/connection.py
  redisvl/utils/utils.py
  tests/conftest.py
  tests/integration/test_async_search_index.py
  tests/integration/test_connection.py
  tests/integration/test_flow.py
  tests/integration/test_flow_async.py
  tests/integration/test_llmcache.py
  tests/integration/test_query.py
  tests/integration/test_search_index.py
  tests/integration/test_search_results.py
  tests/unit/test_utils.py
Labels: maintenance

#288 Release 0.4.0
  README.md
  docs/overview/cli.ipynb
  pyproject.toml
  redisvl/version.py
Labels: release
