Repository redis/redis-vl-python, pull requests merged in 2025-04, with the labels that each got.

#303 Add support for full text queries and hybrid search queries
  poetry.lock
  pyproject.toml
  redisvl/index/index.py
  redisvl/query/__init__.py
  redisvl/query/aggregate.py
  redisvl/query/query.py
  tests/conftest.py
  tests/integration/test_aggregation.py
  tests/integration/test_query.py
  tests/unit/test_aggregation_types.py
  tests/unit/test_query_types.py
Labels: enhancement

#315 Widen ml-dtypes pkg range
  .github/workflows/test.yml
  docs/overview/cli.ipynb
  poetry.lock
  pyproject.toml
  redisvl/version.py
Labels: bug, release

#316 Add a drop_documents() method to search index classes
  .github/workflows/test.yml
  docs/overview/cli.ipynb
  poetry.lock
  pyproject.toml
  redisvl/index/index.py
  redisvl/version.py
  tests/integration/test_async_search_index.py
  tests/integration/test_search_index.py
Labels: enhancement

#318 Add embeddings cache
  README.md
  docs/api/cache.rst
  docs/user_guide/03_llmcache.ipynb
  docs/user_guide/04_vectorizers.ipynb
  docs/user_guide/09_threshold_optimization.ipynb
  docs/user_guide/10_embeddings_cache.ipynb
  docs/user_guide/index.md
  docs/user_guide/release_guide/0_5_0_release.ipynb
  redisvl/extensions/__init__.py
  redisvl/extensions/cache/__init__.py
  redisvl/extensions/cache/base.py
  redisvl/extensions/cache/embeddings/__init__.py
  redisvl/extensions/cache/embeddings/embeddings.py
  redisvl/extensions/cache/embeddings/schema.py
  redisvl/extensions/cache/llm/__init__.py
  redisvl/extensions/cache/llm/base.py
  redisvl/extensions/cache/llm/schema.py
  redisvl/extensions/cache/llm/semantic.py
  redisvl/extensions/constants.py
  redisvl/extensions/llmcache/__init__.py
  redisvl/extensions/llmcache/base.py
  redisvl/extensions/llmcache/schema.py
  redisvl/extensions/llmcache/semantic.py
  redisvl/utils/optimize/cache.py
  redisvl/utils/utils.py
  redisvl/utils/vectorize/base.py
  tests/integration/test_embedcache.py
  tests/integration/test_llmcache.py
  tests/integration/test_threshold_optimizer.py
  tests/unit/test_embedcache_schema.py
  tests/unit/test_llmcache_schema.py
Labels: enhancement

#320 Enable embedding caching on all vectorizers
  docs/user_guide/10_embeddings_cache.ipynb
  poetry.lock
  redisvl/extensions/cache/__init__.py
  redisvl/extensions/cache/base.py
  redisvl/extensions/cache/llm/semantic.py
  redisvl/extensions/router/schema.py
  redisvl/extensions/router/semantic.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/utils/vectorize/base.py
  redisvl/utils/vectorize/text/azureopenai.py
  redisvl/utils/vectorize/text/bedrock.py
  redisvl/utils/vectorize/text/cohere.py
  redisvl/utils/vectorize/text/custom.py
  redisvl/utils/vectorize/text/huggingface.py
  redisvl/utils/vectorize/text/mistral.py
  redisvl/utils/vectorize/text/openai.py
  redisvl/utils/vectorize/text/vertexai.py
  redisvl/utils/vectorize/text/voyageai.py
  tests/integration/test_llmcache.py
  tests/integration/test_vectorizers.py
Labels: enhancement

#323 Rename session manager classes to message history
  README.md
  docs/api/index.md
  docs/user_guide/07_message_history.ipynb
  docs/user_guide/index.md
  redisvl/extensions/constants.py
  redisvl/extensions/message_history/__init__.py
  redisvl/extensions/message_history/base_history.py
  redisvl/extensions/message_history/message_history.py
  redisvl/extensions/message_history/schema.py
  redisvl/extensions/message_history/semantic_history.py
  redisvl/extensions/session_manager/__init__.py
  redisvl/extensions/session_manager/base_session.py
  redisvl/extensions/session_manager/schema.py
  redisvl/extensions/session_manager/semantic_session.py
  redisvl/extensions/session_manager/standard_session.py
  tests/integration/test_message_history.py
  tests/unit/test_message_history_schema.py
Labels: enhancement

#322 Enable semantic router reference updates
  docs/user_guide/08_semantic_router.ipynb
  docs/user_guide/router.yaml
  redisvl/extensions/router/schema.py
  redisvl/extensions/router/semantic.py
  redisvl/index/index.py
  redisvl/utils/optimize/router.py
  redisvl/utils/optimize/utils.py
  redisvl/utils/utils.py
  schemas/semantic_router.yaml
  tests/integration/test_semantic_router.py
  tests/integration/test_threshold_optimizer.py
Labels: enhancement

#326 Changes default cache embedding model
  docs/user_guide/03_llmcache.ipynb
  redisvl/extensions/cache/llm/semantic.py
  tests/integration/test_llmcache.py
Labels: enhancement

#330 Add a lazy_import utility function (part one of our lazy import strategy)
  redisvl/utils/utils.py
  tests/unit/test_utils.py
Labels: enhancement

#329 Remove non-essential tabulate and coloredlogs dependencies
  poetry.lock
  pyproject.toml
  redisvl/cli/index.py
  redisvl/cli/stats.py
  redisvl/utils/log.py
Labels: enhancement

#327 Semantic router testing name generation
  schemas/semantic_router.yaml
  tests/integration/test_semantic_router.py
  tests/integration/test_threshold_optimizer.py
Labels: maintenance
